name: My First Workflow

on: push

jobs:
  first_job:
     runs_on: ubuntu-latest
     steps:
      -name: Welcome Message
        run: echo "My First Github Actions Job"

       -name: List Files
         run: ls
